# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'translate' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for translate

pod ‘RNActivityView'
pod 'AFNetworking', '~> 3.0'
pod ‘BIZPopupView'

end
